version: 2.1

# Define the jobs we want to run for this project
jobs:
    create_infrastructure:
        docker:
          - image: amazon/aws-cli
        steps:
          - checkout
          - run:
              name: Create Cloudformation Stack 
              command: | 
                aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region ${AWS_DEFAULT_REGION}

# Sequential workflow
workflows:
    # Name the workflow
    create_infrastructure_wf:
      jobs:
        - create_infrastructure
