---
- name: Add the group 'prometheus'
  group:
    name: prometheus

- name: Add the user 'prometheus' with primary group 'prometheus'
  user:
    name: prometheus
    group: prometheus
    comment: prometheus user

- name: Creates /etc/prometheus directory
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: Creates /var/lib/prometheus directory
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: Download prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
    dest: /tmp/prometheus-2.19.0.linux-amd64.tar.gz
    mode: '0444'

- name: Extract prometheus-2.19.0.linux-amd64.tar.gz
  unarchive:
    src: /tmp/prometheus-2.19.0.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy file prometheus
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/prometheus
    dest: /usr/local/bin
    owner: prometheus
    group: prometheus
    remote_src: yes
    mode: preserve

- name: Copy file promtool
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/promtool
    dest: /usr/local/bin
    owner: prometheus
    group: prometheus
    remote_src: yes
    mode: preserve

- name: Copy directory consoles
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/consoles
    dest: /etc/prometheus
    owner: prometheus
    group: prometheus
    remote_src: yes
    mode: preserve
    directory_mode: preserve

- name: Copy directory console_libraries
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/console_libraries
    dest: /etc/prometheus
    owner: prometheus
    group: prometheus
    remote_src: yes
    mode: preserve
    directory_mode: preserve

- name: Remove prometheus-2.19.0.linux-amd64.tar.gz
  file:
    path: /tmp/prometheus-2.19.0.linux-amd64.tar.gz
    state: absent

- name: Creating file /etc/prometheus/prometheus.yml
  copy:
    src: "prometheus.yml"
    dest: "/etc/prometheus/prometheus.yml"
    owner: prometheus
    group: prometheus

- name: Creating file /etc/systemd/system/prometheus.service
  copy:
    src: "prometheus.service"
    dest: "/etc/systemd/system/prometheus.service"
    owner: prometheus
    group: prometheus

- name: Enable service prometheus, also issue daemon-reload to pick up config changes
  systemd:
    name: prometheus
    daemon_reload: true
    enabled: true
